remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
header_pages:
  - index.md
  - docs.md
  - blog.md
  - gallery.md
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://wildeLinde.github.io/" }
url: 'https://wildeLinde.github.io/'
baseurl: ''
imagesurl: "/assets/img/"
thumbsurl: "/assets/thumbs/"
